In [ ]:
import keras
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Conv2D,Flatten,Dense,Dropout,MaxPooling2D
from keras import backend as k

Using TensorFlow backend.


In [ ]:
img_rows,img_cols=32,32

# New Section

In [ ]:
### Split the data as train and test
(x_train,y_train),(x_test,y_test)=cifar10.load_data()

170500096/170498071 [==============================] - 4s 0us/step


In [ ]:
x_train[1]

array([[[154, 177, 187],
        [126, 137, 136],
        [105, 104,  95],
        ...,
        [ 91,  95,  71],
        [ 87,  90,  71],
        [ 79,  81,  70]],

       [[140, 160, 169],
        [145, 153, 154],
        [125, 125, 118],
        ...,
        [ 96,  99,  78],
        [ 77,  80,  62],
        [ 71,  73,  61]],

       [[140, 155, 164],
        [139, 146, 149],
        [115, 115, 112],
        ...,
        [ 79,  82,  64],
        [ 68,  70,  55],
        [ 67,  69,  55]],

       ...,

       [[175, 167, 166],
        [156, 154, 160],
        [154, 160, 170],
        ...,
        [ 42,  34,  36],
        [ 61,  53,  57],
        [ 93,  83,  91]],

       [[165, 154, 128],
        [156, 152, 130],
        [159, 161, 142],
        ...,
        [103,  93,  96],
        [123, 114, 120],
        [131, 121, 131]],

       [[163, 148, 120],
        [158, 148, 122],
        [163, 156, 133],
        ...,
        [143, 133, 139],
        [143, 134, 142],
        [143, 133, 144]]

In [ ]:
if k.image_data_format() =='channel_first':
    x_train = x_train.reshape(x_train.shape[0],3,img_rows,img_cols)
    x_test = x_test.reshape(x_test.shape[0],3,img_rows,img_cols)
    input_shape=(3,img_rows,img_cols)
else:
    x_train = x_train.reshape(x_train.shape[0],img_rows,img_cols,3)
    x_test = x_test.reshape(x_test.shape[0],img_rows,img_cols,3)
    input_shape=(img_rows,img_cols,3)


In [ ]:
x_train.shape

(50000, 32, 32, 3)

In [ ]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train/=255
x_test/=255
print("reshape image",x_train.shape[0])

reshape image 50000


In [ ]:
x_train[1]

array([[[0.6039216 , 0.69411767, 0.73333335],
        [0.49411765, 0.5372549 , 0.53333336],
        [0.4117647 , 0.40784314, 0.37254903],
        ...,
        [0.35686275, 0.37254903, 0.2784314 ],
        [0.34117648, 0.3529412 , 0.2784314 ],
        [0.30980393, 0.31764707, 0.27450982]],

       [[0.54901963, 0.627451  , 0.6627451 ],
        [0.5686275 , 0.6       , 0.6039216 ],
        [0.49019608, 0.49019608, 0.4627451 ],
        ...,
        [0.3764706 , 0.3882353 , 0.30588236],
        [0.3019608 , 0.3137255 , 0.24313726],
        [0.2784314 , 0.28627452, 0.23921569]],

       [[0.54901963, 0.60784316, 0.6431373 ],
        [0.54509807, 0.57254905, 0.58431375],
        [0.4509804 , 0.4509804 , 0.4392157 ],
        ...,
        [0.30980393, 0.32156864, 0.2509804 ],
        [0.26666668, 0.27450982, 0.21568628],
        [0.2627451 , 0.27058825, 0.21568628]],

       ...,

       [[0.6862745 , 0.654902  , 0.6509804 ],
        [0.6117647 , 0.6039216 , 0.627451  ],
        [0.6039216 , 0

In [ ]:
type(y_train)

numpy.ndarray

In [ ]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [ ]:
### Convert the class vectors to binary classes
## utils. to_categorical is used to convert array of labeled data(from 0 to nb_classes-1) to one-hot vector.
y_train = keras.utils.to_categorical(y_train,10)
y_test = keras.utils.to_categorical(y_test,10)

In [ ]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
###Model Initialization
model = Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=input_shape))
model.add(Conv2D(64,kernel_size=(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dense(10,activation='softmax'))


In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adadelta',metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,batch_size=10,epochs=5,verbose=1,validation_data=(x_test,y_test))

Train on 50000 samples, validate on 10000 samples
Epoch 1/5
50000/50000 [==============================] - 264s 5ms/step - loss: 1.2767 - accuracy: 0.5492 - val_loss: 1.0159 - val_accuracy: 0.6508
Epoch 2/5
50000/50000 [==============================] - 269s 5ms/step - loss: 0.9011 - accuracy: 0.6896 - val_loss: 0.9674 - val_accuracy: 0.6696
Epoch 3/5
50000/50000 [==============================] - 269s 5ms/step - loss: 0.7306 - accuracy: 0.7496 - val_loss: 0.9061 - val_accuracy: 0.6956
Epoch 4/5
50000/50000 [==============================] - 268s 5ms/step - loss: 0.5850 - accuracy: 0.8013 - val_loss: 0.9265 - val_accuracy: 0.6924
Epoch 5/5
50000/50000 [==============================] - 267s 5ms/step - loss: 0.4574 - accuracy: 0.8470 - val_loss: 1.0292 - val_accuracy: 0.6955


In [ ]:
score=model.evaluate(x_test,y_test,verbose=0)

In [ ]:
print("test loss :",score[0])
print("test accuracy :",score[1])

test loss : 1.0291788902282715
test accuracy : 0.6955000162124634


In [ ]:
test_pred = model.predict(x_test)

In [ ]:
import numpy as np
(np.argmax(test_pred,axis=1)!=np.argmax(y_test,axis=1)).sum()

3045